<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Suchi" name="parallel.ParallelRun" tests="3" failures="1" timestamp="2022-05-12T19:23:33 IST" time="43.882" errors="0">
  <testcase name="runScenario" time="12.983" classname="parallel.ParallelRun"/>
  <system-out/>
  <testcase name="runScenario" time="17.018" classname="parallel.ParallelRun"/>
  <system-out/>
  <testcase name="runScenario" time="13.881" classname="parallel.ParallelRun">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at parallel.Homepagestepdefinition.user_gets_home_section(Homepagestepdefinition.java:51)
at âœ½.user gets Home section(classpath:parallel/Homepage.feature:11)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- parallel.ParallelRun -->
